### ISSUE TITLE
complie error

### ISSUE THREAD

**Issue by ragelancer** [zs6buj/Frsky2Mavlink#4]
Hi，
I compiled the 0.14 version compiled in  Arduino IDE  got some error.

```
too few arguments to function 'uint16_t mavlink_msg_gps_raw_int_pack(uint8_t, uint8_t, mavlink_message_t*, uint64_t, uint8_t, int32_t, int32_t, int32_t, uint16_t, uint16_t, uint16_t, uint16_t, uint8_t, int32_t, uint32_t, uint32_t, uint32_t, uint32_t, uint16_t)'

too few arguments to function 'uint16_t mavlink_msg_statustext_pack(uint8_t, uint8_t, mavlink_message_t*, uint8_t, const char*, uint16_t, uint8_t)'
```
I compared it with the 0.13 version, it seems like missing some arguments.

**Comment by zs6buj** [comment]
Yes, unfortunately I originally developed the translator for myself, and those were simply an evolution of development.

It's always a good idea to use a recent version. :)  May I suggest 2.60.4. Just set up the config.h correctly.

**Comment by ragelancer** [comment]
Hi Eric.
Thanks for your relay. Are you referring to the mavlinktopassthru project?  However, I want to compile the frsky2mavlink project.
The error occurs in Frsky2Mavlinkv0.14.ino line989 and line1108

**Comment by zs6buj** [comment]
Ah, yes sorry. I'm all over the place.

I believe that is a change in the mavlink library. I have a busy day tomorrow,  but I think I simply got the latest library. I'll check it out.

**Comment by zs6buj** [comment]
Yes I checked this. Simply get the latest Ardupilot/mavlink libraries from [github](https://github.com/ArduPilot/ardupilot)

![image](https://user-images.githubusercontent.com/12892533/85367169-075c5680-b529-11ea-893d-94db58e5ad45.png)

**Comment by ragelancer** [comment]
Hi Eric.
I can't find any mavlink libraries from the link you posted.
I get the libraries from https://github.com/mavlink/c_library_v2
The 0.13 version works well with these libraries, but the 0.14 version does not.
![image](https://user-images.githubusercontent.com/27507405/85396762-dd388200-b584-11ea-94bf-619bc0220bee.png)

**Comment by zs6buj** [comment]
Could you please try these libraries|:

[https://github.com/zs6buj/MavlinkToPassthru/tree/master/libraries](url)

**Comment by ragelancer** [comment]
THx Eric.
I think this error is using the differences version of mavlink_msg_gps_raw_int.h library.  I cant find the library which you used, but the 0.13 version compiled without error. So I will stick to the 0.13 version.
However, I got another problem. I flashed the project to an esp32 board, the board stuck in reboot looping.
The debug file is as follows.
[esp32debug.txt](https://github.com/zs6buj/Frsky2Mavlink/files/4842066/esp32debug.txt)

**Comment by ragelancer** [comment]
My usage scenario is as follows:
fc f405-wing with ardupilot firmware
rx r9mm
tx jumper t16 with r9m module
I want to connect r9m sport pin to esp32. Convert sport telementry to mavlink, pairing a phone or laptop to esp32 via bluetooth link.
If I dont connect r9m to esp32, the board seems working alright. When I connect r9m sport pin to esp 13 pin, the board reboot again and again.
I guess min esp32 board is broken, but not sure. Could you post the bin file, I can upgrade the esp32 OTA and try it again.

**Comment by zs6buj** [comment]
Hi ragelancer

There is probably nothing wrong with your board. The ESP32 does not like some pins, like 12,13, 14  high while it is booting.  This is not a problem in ground mode. Just power up the ESP first, but in relay or air mode it's a pest. I have not really applied my mind to this issue yet. Maybe you could try different pins. One work around is to pull pin 13 down to ground  until its up and running. Or delay powering up the r9 receiver.

I have to think about this some more and find a better solution.

**Comment by zs6buj** [comment]
Which version binary do you need, and with which settings?

**Comment by zs6buj** [comment]
To be clear, it's the S.Port RX pin on the ESP32 that causes the problem. In Ground Mode, you don't need it.

In Air or Relay  mode, most guys use the Teensy 3.x, which does not have the problem, as the problem is related to WiFi.

**Comment by zs6buj** [comment]
I realise you are talking about FrskyToMavlink, but the same applies to the pin high problem. You should try to get the latest version working

**Comment by ragelancer** [comment]
Thanks for your patience Eric.

I compiled two types of firmware, one with default settings and the other without wifi bt oled web etc. Tried to define different pins as FrRx_Pin likes pin 1 8 25 32 44. And power R9m module after esp32.

But none of them works. If I don't power R9m module, they all boot  normally and the FrsStatusLed  blinks. Once R9m module is powered, the led is always on, but  debug shows that the esp32 keeps rebooting. 

Even if R9m module is disconnected, just touching the FrRx_Pin with my finger will cause the esp32 board to reboot.

I think there is nothing wrong with the wiring, debug shows that the esp32 board gets the battery capacity information from smart port protocol, but that's it, then the error occurs and the board reboots.

```
Starting Frsky2Mavlinkv0.13 .....
EEPROM initialised successfully
Target Board is ESP32 / Variant is Dev Module
Mavlink Serial Out
No WiFi options selected, WiFi support not compiled in
No Bluetooth options selected, BT support not compiled in
S.Port on ESP is inverted and is on rx pin = 13
Mavlink serial output on pins rx = 16 and tx = 17
Frsky 5007: Bat1 capacity=3300
Frsky 5007: Bat1 capacity=3300
Guru Meditation Error: Core  0 panic'ed (InstrFetchProhibited). Exception was unhandled.
Core 0 register dump:
PC      : 0x00400d85  PS      : 0x00060130  A0      : 0x8008a340  A1      : 0x3ffbc070  
A2      : 0x00000000  A3      : 0x00000000  A4      : 0x00000001  A5      : 0x80000020  
A6      : 0x00000000  A7      : 0x3ffbbbc4  A8      : 0x800d89b0  A9      : 0x3ffc1424  
A10     : 0x00400d85  A11     : 0x00000001  A12     : 0x00000000  A13     : 0x00000001  
A14     : 0x00060120  A15     : 0x00000000  SAR     : 0x00000000  EXCCAUSE: 0x00000014  
EXCVADDR: 0x00400d84  LBEG    : 0x00000000  LEND    : 0x00000000  LCOUNT  : 0x00000000  

Backtrace: 0x00400d85:0x3ffbc070 0x4008a33d:0x3ffbc090 0x40088b49:0x3ffbc0b0

Rebooting...
ets Jun  8 2016 00:22:57
```

If possible, could you compile the last version with default settings for esp32 dev board. I will upgrade OTA and try it again.

**Comment by zs6buj** [comment]
No problem at all. My apologies for not giving this my full attention before. I've been crazy busy on an other project. :)

Ok, I added a lib folder, and the binary you requested. The settings are appear below|:

The boot problem with WiFi and certain pins high will not just go away I'm afraid. We need to find an answer :)

```
#define webSupport                      // ESP only. Enable wifi web support, including OTA firmware updating. Browse to IP.
#define webPassword      "changeme!"    // Web password 
//#define Reset_Web_Defaults            // Settings in eeprom. Do this if eeprom settings are corrupt or wrong.

//#define SD_Support                    // Enable if you have an SD card reader attached
#define OLED_Support                  // Enable if you have an OLED display attached
                                 
#define frBaud                 57600    // S.Port baud setting - default 57600 

#define ESP_SPort_Invert                // Does what it says

#define PlusVersion  // Added support for 0x5009 Mission WPs, 0x50F1 Servo_Channels, 0x50F2 VFR_Hud


//=================================================================================================
//           D E F A U L T   G R O U N D S T A T I O N    I / O   S E T T I N G S   
//=================================================================================================
// Choose only one of these default GCS-side I/O channels
// How does Mavlink telemetry leave this translator?

#define GCS_Mavlink_IO  0    // Serial Port2     
//#define GCS_Mavlink_IO  1    // BlueTooth Classic - ESP32 only
#define GCS_Mavlink_IO  2    // WiFi - ESP32 or ESP8266 only - auto selects on ESP8266
//#define GCS_Mavlink_IO  3    // WiFi AND Bluetooth simultaneously - ESP32 only

// NOTE: The Bluetooth class library uses a lot of application memory. During Compile/Flash
//       you may need to select Tools/Partition Scheme: "Minimal SPIFFS (1.9MB APP ...) or similar

//#define GCS_Mavlink_SD       // SD Card - ESP32 only - mutually inclusive with other GCS I/O

//=================================================================================================                             
//                          S E L E C T   E S P   B O A R D   V A R I A N T   
//=================================================================================================

#define ESP32_Variant     1    //  ESP32 Dev Module - Use Partition Scheme: "Minimal SPIFFS(1.9MB APP...)"
//#define ESP32_Variant     2    //  Wemos® LOLIN ESP32-WROOM-32_OLED_Dual_26p
//#define ESP32_Variant     3    //  Dragonlink V3 slim with internal ESP32 - contributed by Noircogi
//#define ESP32_Variant     4    //  Heltec Wifi Kit 32 - Use Partition Scheme: "Minimal SPIFFS(Large APPS ith OTA)" - contributed by Noircogi

#define ESP8266_Variant   1   // NodeMCU ESP 12F - choose "NodeMCU 1.0(ESP-12E)" board in the IDE
//#define ESP8266_Variant   2   // ESP-12E, ESP-F barebones boards. RFD900X TX-MOD, QLRS et al - use Generic ESP8266 on IDE


//=================================================================================================
//                      D E F A U L T   B L U E T O O T H   S E T T I N G S   
//=================================================================================================

#define BT_Mode  1           // Master Mode - we advertise the "host" name and slave connects to us
//#define BT_Mode  2           // Slave Mode - we connect as slave to a master
#define BT_ConnectToSlave     "Crossfire 0277"  // Example


//=================================================================================================
//                            D E F A U L T    W  I  F  I    S E T T I N G S   
//=================================================================================================

#define HostName             "PassToMav"            // This translator's host name
#define APssid               "PassthruToMavlink"    // The AP SSID that we advertise   ====>
#define APpw                 "password"             // Change me!
#define APchannel            9                      // The wifi channel to use for our AP
#define STAssid              "OmegaOffice"          // Target AP to connect to         <====
#define STApw                "changeme!"            // Target AP password        

#define Start_WiFi                       // Start WiFi at startup, override startWiFi Pin

// Choose one default mode for ESP only - AP means advertise as an access point (hotspot). STA means connect to a known host
//#define WiFi_Mode   1  //AP            
//#define WiFi_Mode   2  // STA
#define WiFi_Mode   3  // STA failover to AP

// Choose one default protocol - for ESP32 only
//#define WiFi_Protocol 1    // TCP/IP
#define WiFi_Protocol 2    // UDP 


//=================================================================================================
//                            O T H E R   U S E R   O P T I O N S  
//=================================================================================================

#define SPort_Serial        1         // Teensy port1=pin1, port3=pin8. The default is Serial 1, but 3 is possible 


//================================== Set your time zone here ======================================
// Only for SD / TF Card adapter option
// Date and time determines the TLog file name only
//const float Time_Zone = 10.5;    // Adelaide, Australia
const float Time_Zone = 2.0;    // Jo'burg
bool daylightSaving = false;

//=================================================================================================
//                        E X P E R I M E N T A L    O P T I O N S  
//    Don't change anything here unless you are confident you know the outcome

//#define ESP32_SoftwareSerial    // otherwise HardwareSerial is used 
//#define ESP_Onewire             // enable half_duplex on single (tx) pin and wire 
//#define ESP_Air_Relay_Blind_Inject_OK  // Blind inject instead of interleaving
```

**Comment by ragelancer** [comment]
Thanks for your help Eric, I've flashed the bin files you provided but the problem is still there. I've ordered a new esp32 board and will give you further feedback when it arrives.

**Comment by ragelancer** [comment]
Hello, Eric. it's me again.

I bought a new esp32 board and an esp8266 board. After compiling and flash the 0.14 firmware neither works properly. the esp32 board stuck in reboot loop as soon as s-port rx pin got a signal, the esp8266 board shows "frs lost".

All the three boards, I have flashed your AntTracker project for testing and they all can recognize the s-port signal properly, so I think there should be no problem with the hardware.

If you finish your current project, could you take the time to check the code of the Frsky2Mavlink project?
Thanks again for your patience and help.

**Comment by zs6buj** [comment]
Hi ragelancer 

Which 32 board are you using? I can look at it right now.

EDIT:

and which pin are you using for the S.Port?

**Comment by ragelancer** [comment]
Hi Eric.
 I got 2 esp32 board. One is 30 pin, another is 38 pin.
They look like these
![image](https://user-images.githubusercontent.com/27507405/87652722-27c5ac80-c787-11ea-845e-09120b05a323.png)
![image](https://user-images.githubusercontent.com/27507405/87652761-33b16e80-c787-11ea-834d-c0be7d523d57.png)

**Comment by zs6buj** [comment]
OK, those are "Dev Kit" boards by the looks of it.  Which pin are you using for S.Port ?

**Comment by ragelancer** [comment]
Default pin 13. I also try different pins like  18 19 25 26.

**Comment by zs6buj** [comment]
I switched S.Port to Serial2 and it seems to be stable now. Serial1 is an "orphan" uart on the esp32 and most boards don't even try to implement it. 

It's working for me now on a Heltec wifi kit 32 board, but the dev boards should also work.

I switched on the esp8266 boards as well, but did not test.

v0.15 on my GitHub.

**Comment by ragelancer** [comment]
Thanks Eric.
 It still doesn't work. This is my ide setting, is there anything wrong?
My use case is R9m module s-port ===> esp32 board.
![image](https://user-images.githubusercontent.com/27507405/87785341-97609800-c86a-11ea-9344-a44fe5b79cc2.png)

**Comment by zs6buj** [comment]
Ok, so now it's stable, right? It's not rebooting all the time.

May I ask how you are getting the S.Port telemetry from the R9M while it is plugged in? I assume you are tapping into the bottom pin (telem) and the ground pin, one up.

**Comment by ragelancer** [comment]
Hi Erci.
 It doesn't work for me, I still got the reboot problem.
I connected R9m and esp32 with 2 wires. 

R9m             esp32
s.port===>pin13
gnd=====>gnd

 like this
![Screenshot_20200718-144259__01](https://user-images.githubusercontent.com/27507405/87846828-76995080-c905-11ea-9871-7f867dfb7692.jpg)

And I think the telem pin is the up one, gnd pin is the bottom one.

**Comment by zs6buj** [comment]
I made a video of it working on my ESP32 Dev Board.

https://photos.app.goo.gl/nayfvLc6CwcF8x4X8

However, while I was unplugging everything, I observed that the board started rebooting. This happened after I unplugged the twin wires (white and black) from the back of the Horus. And it went into a perpetual rebooting loop, until I pulled the connector off pin 13.

So, the pins are VERY high impedance CMOS, and float high very quickly. Once that pin is high, the rebooting starts. It seems to tolerate the 3.3v  telemetry just fine.

 I'm rather busy today, but maybe you could try a high value pull-down on pin 13, say 500k - 100k.

**Comment by ragelancer** [comment]
Hi Eric.

I swapped the s.port to serial2 and added a 100k ohm resistor. Things are better, but it still reboots within 5 minutes of starting.

I don't think it's a hardware issue, but maybe the  code needs some  tuning.

1. From the beginning, I thought it might be the ttl level causing the reboot problem, so I added ttl level converter between r9m and esp32. But it still reboots occasionally.

2. With the same esp32 board , the same serial port and the same pins. After flashed your antenna tracker project, even without resistors or ttl level converters, it works fine without rebooting.

Anyway, thank you so much for creating this great project. I  compiled the 0.10 version for stm32  blue pill, and it works fine.

PS: The 0.10 version has some minor mistakes, I've fixed it, but don't know how to upload it to gitlthub.

**Comment by zs6buj** [comment]
Thanks for the feedback.  It's always welcom. :)

_PS: The 0.10 version has some minor mistakes, I've fixed it, but don't know how to upload it to gitlthub._

Maybe just zip the code to me and ill update it.

**Comment by ragelancer** [comment]
Hi Eric.
Sorry for the delay.
The stm32 blue pill `Serial begin()` is for USB virtual serial. `Serial1 begini()` is for usart1.
So I changed `Serial2` to `Serial3`, `Serial1` to `Serial2` and `Serial` to `Serial1`.
[Frsky2Mavlinkv0.10_forbluepill.zip](https://github.com/zs6buj/Frsky2Mavlink/files/4959802/Frsky2Mavlinkv0.10_forbluepill.zip)

**Comment by zs6buj** [comment]
Thank you ragelancer. I've added it as an option on the code repo

**Comment by befut8** [comment]
hi ragelancer, can you please help me on the bluepill :

. where do you buy it (reference)
. do you have the wiring of the bluepill corresponding to the zip file above

thanks
